# Generated by Django 3.2.4 on 2021-11-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
