# Generated by Django 3.2.4 on 2021-11-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuarios_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
